# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/edit_atal_AES_v1_0.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/edit_atal_AES_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0
  c:/Xilinx/Vivado/MyProjects/myIps/ip_repo/sevenSegment_1.0
  c:/Xilinx/Vivado/MyProjects/myIps/ip_repo/led_ip_1.0
} [current_project]
set_property ip_output_repo c:/Xilinx/Vivado/MyProjects/myIps/ip_repo/edit_atal_AES_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/aescore.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/hdl/atal_AES_v1_0_S_AXI.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/dataAddrCounter.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/dataBuffer.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/keyAddrCounter.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/keyBuffer.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/mixcolumn.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/rounds.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/rounndlast.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/sbox.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/src/subbytes.v
  C:/Xilinx/Vivado/MyProjects/myIps/ip_repo/atal_AES_1.0/hdl/atal_AES_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top atal_AES_v1_0 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef atal_AES_v1_0.dcp

catch { report_utilization -file atal_AES_v1_0_utilization_synth.rpt -pb atal_AES_v1_0_utilization_synth.pb }
